import { Header } from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'
import { NavBar } from '@/components/navBar/NavBar'
import { Footer } from '@/components/footer/Footer'

const openSans = Open_Sans({ subsets: ["latin"], weight: ['300', "400", "500", '700'], variable: "--font-sans" })

export const metadata: Metadata = {
    title: 'Balanz University',
    description: 'Generated by create next app',
}


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${openSans.variable} font-sans flex flex-col h-screen`}>
                <Header />
                <NavBar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
